#!/usr/bin/env bash
# File name fibi

function fib {
        if [[ $1 -eq 1 ]]
        then
                echo 0
        elif [[ $1 -eq 2 ]]
        then
                echo -n 0" "
                echo 1
        else
                local count=$1
                local first=0
                echo -n $first" "
                local second=1
                echo -n $second" "
                while [[ count -gt 2 ]]
                do
                        let third=second+first
                        echo -n $third" "
                        let first=second
                        let second=third
                        let count-=1
                done
        echo $'\n'
        fi
}

